from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from objects.api import API
from objects.cloud import Cloud
from objects.enrichment import Enrichment
from objects.remediation import Remediation
from objects.resource_details import ResourceDetails
from pydantic import BaseModel


class ActivityID(str, Enum):
    """
    The normalized identifier of the finding activity.

    0 Unknown: The event activity is unknown.
    1 Create: A finding was created.
    2 Update: A finding was updated.
    3 Close: A finding was closed.
    99 Other: The event activity is not mapped. See the activity_name attribute, which contains a data source specific value.
    """

    Unknown = 0
    Create = 1
    Update = 2
    Close = 3
    Other = 99


class CategoryUID(str, Enum):
    """
    The category unique identifier of the event.

    2 Findings: Findings events report findings, detections, and possible resolutions of malware, anomalies, or other actions performed by security products.
    """

    Findings = 2


class ClassUID(str, Enum):
    """
    The unique identifier of a class. A Class describes the attributes available in an event.

    2004 DetectionFinding: A Detection Finding describes detections or alerts generated by security products using correlation engines, detection engines or other methodologies. Note: if the product is a security control, the security_control profile should be applied and its attacks information should be duplicated into the finding_info object.
    """

    DetectionFinding = 2004


class Detection(BaseModel):
    """
    A Detection Finding describes detections or alerts generated by security products using correlation engines, detection engines or other methodologies. Note: if the product is a security control, the security_control profile should be applied and its attacks information should be duplicated into the finding_info object.

    Attributes:
    - Activity (activity_name) [Optional]: The finding activity name, as defined by the activity_id.
    - Activity ID (activity_id): The normalized identifier of the finding activity.
    - Affected Resources (resources) [Recommended]: Describes details about resources that were the target of the activity that triggered the finding.
    - Category (category_name): The event category name, as defined by category_uid value: Findings.
    - Class (class_name) [Optional]: The event class name, as defined by class_uid value: Detection Finding.
    - Class ID (class_uid): The unique identifier of a class. A Class describes the attributes available in an event.
    - Comment (comment) [Optional]: A user provided comment about the finding.
    - Confidence (confidence) [Optional]: The confidence, normalized to the caption of the confidence_id value. In the case of 'Other', it is defined by the event source.
    - Confidence ID (confidence_id) [Optional]: Represents the accuracy of the detection rule. A low confidence indicates a broad finding scope that may include benign events.
    - Confidence Score (confidence_score) [Optional]: A numerical score reflecting the confidence level.
    - Count (count) [Optional]: Number of times similar events occurred within a specified timeframe.
    - Duration (duration) [Optional]: Time span of the event, from start to end, in milliseconds.
    - End Time (end_time) [Optional]: Timestamp of the most recent event included in the finding.
    - Enrichments (enrichments) [Optional]: Additional information from external sources associated with the finding.
    - Event Time (time) [Required]: The standardized time when the event occurred or the finding was created.
    - Evidence Artifacts (evidences) [Optional]: Artifacts related to the security detection activities.
    - Finding Information (finding_info) [Required]: Details supporting the identification of the finding.
    - Impact, Impact Score, Impact ID (impact, impact_score, impact_id) [Optional]: Describes the effect and severity of the finding.
    - Message (message) [Optional]: Description of the event/finding as defined by the source.
    - Metadata (metadata) [Required]: Data providing context for the event/finding.
    - Observables (observables) [Optional]: Observable elements associated with the event/finding.
    - Raw Data (raw_data) [Optional]: Original data as received from the source.
    - Remediation Guidance (remediation) [Optional]: Suggested steps to address the finding.
    - Risk Level, Risk Score, Risk Level ID (risk_level, risk_score, risk_level_id) [Optional]: The risk associated with the finding.
    - Severity, Severity ID (severity, severity_id) [Required]: The level of severity assigned to the event/finding.
    - Start Time (start_time) [Optional]: Time of the earliest event included in the finding.
    - Status, Status Code, Status Details, Status ID (status, status_code, status_detail, status_id) [Optional]: Current state of the finding.
    - Timezone Offset (timezone_offset) [Optional]: Difference in minutes from UTC.
    - Type ID, Type Name (type_id, type_name) [Required/Optional]: Identifiers for the event's type and description.
    - Unmapped Data (unmapped) [Optional]: Attributes not mapped to the event schema.
    - Vulnerabilities (vulnerabilities) [Optional]: Vulnerabilities identified in the finding.

    """

    api_details: Optional[API]
    activity_name: Optional[str]
    activity_id: ActivityID
    resources: Optional[list[ResourceDetails]]
    category_name: str = "Findings"
    category_uid: CategoryUID = CategoryUID("Findings")
    class_name: Optional[str] = "Detection Finding"
    class_uid: ClassUID = ClassUID("DetectionFinding")
    cloud: Cloud
    comment: Optional[str]
    confidence: Optional[str]
    confidence_id: Optional[int]
    confidence_score: Optional[int]
    count: Optional[int]
    duration: Optional[int]
    end_time: Optional[datetime]
    enrichments: Optional[List[Enrichment]]
    event_time: datetime
    evidences: Optional[List[EvidenceArtifacts]]
    finding_info: FindingInformation
    impact: Optional[str]
    impact_score: Optional[int]
    impact_id: Optional[int]
    metadata: Metadata
    message: Optional[str]
    observables: Optional[List[Observable]]
    raw_data: Optional[str]
    remediation: Optional[Remediation]
    risk_level: Optional[str]
    risk_level_id: Optional[int]
    risk_score: Optional[int]
    severity: Optional[str]
    severity_id: int
    start_time: Optional[datetime]
    status: Optional[str]
    status_code: Optional[str]
    status_detail: Optional[str]
    status_id: Optional[int]
    timezone_offset: Optional[int]
    type_id: int
    type_name: Optional[str]
    unmapped_data: Optional[Dict[str, Any]]
    vulnerabilities: Optional[List[VulnerabilityDetails]]
