from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field

from py_ocsf_models.events.findings.action_id import ActionID
from py_ocsf_models.events.findings.category_uid import CategoryUID
from py_ocsf_models.events.findings.class_uid import ClassUID
from py_ocsf_models.events.findings.detection_finding_type_id import (
    DetectionFindingTypeID,
)
from py_ocsf_models.events.findings.disposition_id import DispositionID
from py_ocsf_models.events.findings.finding import Finding
from py_ocsf_models.events.findings.impact_id import ImpactID
from py_ocsf_models.events.findings.priority_id import PriorityID
from py_ocsf_models.events.findings.risk_level_id import RiskLevelID
from py_ocsf_models.events.findings.status_id import StatusID
from py_ocsf_models.objects.actor import Actor
from py_ocsf_models.objects.api import API
from py_ocsf_models.objects.authorization import AuthorizationResult
from py_ocsf_models.objects.cloud import Cloud
from py_ocsf_models.objects.evidence_artifacts import EvidenceArtifacts
from py_ocsf_models.objects.fingerprint import FingerPrint
from py_ocsf_models.objects.firewall_rule import FirewallRule
from py_ocsf_models.objects.group import Group
from py_ocsf_models.objects.malware import Malware
from py_ocsf_models.objects.remediation import Remediation
from py_ocsf_models.objects.resource_details import ResourceDetails
from py_ocsf_models.objects.ticket import Ticket
from py_ocsf_models.objects.user import User
from py_ocsf_models.objects.verdict import VerdictID
from py_ocsf_models.objects.vulnerability_details import VulnerabilityDetails


class DetectionFinding(Finding, BaseModel):
    """
    A Detection Finding describes detections or alerts generated by security products
    using correlation engines, detection engines or other methodologies.

    OCSF Schema Version: 1.7.0
    Class UID: 2004

    Core Attributes:
    - time [Required]: The standardized time when the event occurred.
    - time_dt [Optional]: The event time in datetime format (DateTime profile).
    - timezone_offset [Optional]: Difference in minutes from UTC (-1080 to 1080).
    - type_uid [Required]: The event/finding type ID.
    - type_name [Optional]: The event/finding type name.

    Cloud Profile Attributes:
    - cloud [Required for Cloud profile]: Cloud environment details.
    - api [Optional]: API call details.

    Security Control Profile Attributes:
    - action_id [Optional]: The action taken by a security control.
    - action [Optional]: The action name.
    - disposition_id [Optional]: The outcome/disposition of the security control.
    - disposition [Optional]: The disposition name.
    - is_alert [Optional]: Whether this is an alertable signal.

    Incident Profile Attributes:
    - verdict_id [Optional]: The incident verdict.
    - verdict [Optional]: The verdict name.
    - priority_id [Optional]: The priority level.
    - priority [Optional]: The priority name.

    Actor and Assignment:
    - actor [Optional]: User/role/process that triggered the finding.
    - assignee [Optional]: User assigned to the finding.
    - assignee_group [Optional]: Group assigned to the finding.

    Security Objects:
    - authorizations [Optional]: Authorization results.
    - firewall_rule [Optional]: Firewall rule that matched.
    - malware [Optional]: Detected malware details.
    - tickets [Optional]: Associated ITSM tickets.

    Resources and Evidence:
    - resources [Recommended]: Affected resources.
    - evidences [Optional]: Evidence artifacts.
    - vulnerabilities [Optional]: Identified vulnerabilities.

    Impact and Risk:
    - impact, impact_id, impact_score [Optional]: Impact assessment (score: 0-100).
    - risk_level, risk_level_id, risk_score, risk_details [Optional]: Risk assessment (score: 0-100).

    Other:
    - count [Optional]: Number of similar events.
    - duration [Optional]: Time span in milliseconds.
    - is_suspected_breach [Optional]: Analytics-based breach determination.
    - src_url [Optional]: URL to the original finding.
    - raw_data_hash [Optional]: Hash of raw_data content.
    - raw_data_size [Optional]: Raw data size in bytes (>= 0).
    - status_id [Optional]: Finding status.
    - remediation [Optional]: Remediation guidance.
    """

    # Category and class identifiers
    category_name: str = CategoryUID.Findings.name
    category_uid: int = CategoryUID.Findings.value
    class_name: Optional[str] = "Detection Finding"
    class_uid: int = ClassUID.DetectionFinding

    # Time fields
    time: int
    time_dt: Optional[datetime] = None
    timezone_offset: Optional[int] = Field(None, ge=-1080, le=1080)

    # Type fields
    type_uid: DetectionFindingTypeID
    type_name: Optional[str] = None

    # Cloud profile fields
    cloud: Optional[Cloud] = None
    api: Optional[API] = None

    # Security Control profile fields
    action_id: Optional[ActionID] = None
    action: Optional[str] = None
    disposition_id: Optional[DispositionID] = None
    disposition: Optional[str] = None
    is_alert: Optional[bool] = None

    # Incident profile fields
    verdict_id: Optional[VerdictID] = None
    verdict: Optional[str] = None
    priority_id: Optional[PriorityID] = None
    priority: Optional[str] = None

    # Actor and assignment
    actor: Optional[Actor] = None
    assignee: Optional[User] = None
    assignee_group: Optional[Group] = None

    # Security objects
    authorizations: Optional[list[AuthorizationResult]] = None
    firewall_rule: Optional[FirewallRule] = None
    malware: Optional[list[Malware]] = None
    tickets: Optional[list[Ticket]] = None

    # Resources and evidence
    resources: Optional[list[ResourceDetails]] = None
    evidences: Optional[list[EvidenceArtifacts]] = None
    vulnerabilities: Optional[list[VulnerabilityDetails]] = None

    # Impact and risk (with Field constraints)
    impact: Optional[str] = None
    impact_id: Optional[ImpactID] = None
    impact_score: Optional[int] = Field(None, ge=0, le=100)
    risk_level: Optional[str] = None
    risk_level_id: Optional[RiskLevelID] = None
    risk_score: Optional[int] = Field(None, ge=0, le=100)
    risk_details: Optional[str] = None

    # Status and remediation
    status_id: Optional[StatusID] = None
    remediation: Optional[Remediation] = None

    # Misc fields
    count: Optional[int] = None
    duration: Optional[int] = None
    is_suspected_breach: Optional[bool] = None
    src_url: Optional[str] = None
    raw_data_hash: Optional[FingerPrint] = None
    raw_data_size: Optional[int] = Field(None, ge=0)
