from datetime import datetime
from enum import IntEnum
from typing import Optional

from pydantic.v1 import BaseModel

from py_ocsf_models.events.base_event import BaseEvent
from py_ocsf_models.objects.finding_info import FindingInformation


class CategoryUID(IntEnum):
    """
    The category unique identifier of the event.

    2 Findings: Findings events report findings, detections, and possible resolutions of malware, anomalies, or other actions performed by security products.
    """

    Findings = 2


class ImpactID(IntEnum):
    """
    The normalized impact of the finding.

    0 Unknown: The normalized impact is unknown.
    1 Low
    2 Medium
    3 High
    4 Critical
    99 Other: The impact is not mapped. See the impact attribute, which contains a data source specific value.
    """

    Unknown = 0
    Low = 1
    Medium = 2
    Hig = 3
    Critical = 4
    Other = 99


class RiskLevelID(IntEnum):
    """
    The normalized risk level id.

    0 Info
    1 Low
    2 Medium
    3 High
    4 Critical
    """

    Info = 0
    Low = 1
    Medium = 2
    High = 3
    Critical = 4


class TypeID(IntEnum):
    """
    The event/finding type ID. It identifies the event's semantics and structure. The value is calculated by the logging system as: class_uid * 100 + activity_id.

    0 Info
    1 Low
    2 Medium
    3 High
    4 Critical
    """

    Unknown = 200400
    Create = 200401
    Update = 200402
    Close = 200403
    Other = 200404


class ClassUID(IntEnum):
    """
    The unique identifier of a class. A Class describes the attributes available in an event.

    2003 ComplianceFinding: Compliance Finding events describe results of evaluations performed against resources, to check compliance with various Industry Frameworks or Security Standards such as NIST SP 800-53, CIS AWS Foundations Benchmark v1.4.0, ISO/IEC 27001 etc. Note: if the event producer is a security control, the security_control profile should be applied and its attacks information, if present, should be duplicated into the finding_info object.
    Note: If the Finding is an incident, i.e. requires incident workflow, also apply the incident profile or aggregate this finding into an Incident Finding.
    """

    ComplianceFinding = 2003

    """
    The unique identifier of a class. A Class describes the attributes available in an event.

    2004 DetectionFinding: A Detection Finding describes detections or alerts generated by security products using correlation engines, detection engines or other methodologies. Note: if the product is a security control, the security_control profile should be applied and its attacks information should be duplicated into the finding_info object. Note: If the Finding is an incident, i.e. requires incident workflow, also apply the incident profile or aggregate this finding into an Incident Finding.
    """
    DetectionFinding = 2004


class StatusID(IntEnum):
    """
    The normalized status identifier of the Finding, set by the consumer.

    0 Unknown: The status is unknown.
    1 New: The Finding is new and yet to be reviewed.
    2 InProgress: The Finding is under review.
    3 Suppressed: The Finding was reviewed, determined to be benign or a false positive and is now suppressed.
    4 Resolved: The Finding was reviewed, remediated and is now considered resolved.
    5 Archived: The Finding was archived.
    99 Other: The event status is not mapped. See the status attribute, which contains a data source specific value.
    """

    Unknown = 0
    New = 1
    InProgress = 2
    Suppressed = 3
    Resolved = 4
    Archived = 5
    Other = 99


class ActivityID(IntEnum):
    """
    The normalized identifier of the finding activity.

    0 Unknown: The event activity is unknown.
    1 Create: A finding was created.
    2 Update: A finding was updated.
    3 Close: A finding was closed.
    99 Other: The event activity is not mapped. See the activity_name attribute, which contains a data source specific value.
    """

    Unknown = 0
    Create = 1
    Update = 2
    Close = 3
    Other = 99


class ConfidenceID(IntEnum):
    """
    The normalized confidence refers to the accuracy of the rule that created the finding. A rule with a low confidence means that the finding scope is wide and may create finding reports that may not be malicious in nature.

    0 Unknown: The normalized confidence is unknown.
    1 Low
    2 Medium
    3 High
    99 Other: The confidence is not mapped to the defined enum values. See the confidence attribute, which contains a data source specific value.

    """

    Unknown = 0
    Low = 1
    Medium = 2
    High = 3
    Other = 99


class DispositionID(IntEnum):
    """
    Describes the outcome or action taken by a security control, such as access control checks, malware detections or various types of policy violations.

    0	Unknown The disposition is unknown.
    1	Allowed Granted access or allowed the action to the protected resource.
    2	Blocked Denied access or blocked the action to the protected resource.
    3	Quarantined A suspicious file or other content was moved to a benign location.
    4	Isolated A session was isolated on the network or within a browser.
    5	Deleted A file or other content was deleted.
    6	Dropped The request was detected as a threat and resulted in the connection being dropped.
    7	Custom Action A custom action was executed such as running of a command script. Use the message attribute of the base class for details.
    8	Approved A request or submission was approved. For example, when a form was properly filled out and submitted. This is distinct from 1 'Allowed'.
    9	Restored A quarantined file or other content was restored to its original location.
    10	Exonerated A suspicious or risky entity was deemed to no longer be suspicious (re-scored).
    11	Corrected A corrupt file or configuration was corrected.
    12	Partially Corrected A corrupt file or configuration was partially corrected.
    13	Uncorrected A corrupt file or configuration was not corrected.
    14	Delayed An operation was delayed, for example if a restart was required to finish the operation.
    15	Detected Suspicious activity or a policy violation was detected without further action.
    16	No Action The outcome of an operation had no action taken.
    17	Logged The operation or action was logged without further action.
    18	Tagged A file or other entity was marked with extended attributes.
    19	Alert The request or activity was detected as a threat and resulted in a notification but request was not blocked.
    20	Count Counted the request or activity but did not determine whether to allow it or block it.
    21	Reset The request was detected as a threat and resulted in the connection being reset.
    22	Captcha Required the end user to solve a CAPTCHA puzzle to prove that a human being is sending the request.
    23	Challenge Ran a silent challenge that required the client session to verify that it's a browser, and not a bot.
    24	Access Revoked The requestor's access has been revoked due to security policy enforcements. Note: use the Host profile if the User or Actor requestor is not present in the event class.
    25	Rejected A request or submission was rejected. For example, when a form was improperly filled out and submitted. This is distinct from 2 'Blocked'.
    26	Unauthorized An attempt to access a resource was denied due to an authorization check that failed. This is a more specific disposition than 2 'Blocked' and can be complemented with the authorizations attribute for more detail.
    27	Error An error occurred during the processing of the activity or request. Use the message attribute of the base class for details.
    99	Other The disposition is not mapped. See the disposition attribute, which contains a data source specific value.
    """

    Unknown = 0
    Allowed = 1
    Blocked = 2
    Quarantined = 3
    Isolated = 4
    Deleted = 5
    Dropped = 6
    CustomAction = 7
    Approved = 8
    Restored = 9
    Exonerated = 10
    Corrected = 11
    PartiallyCorrected = 12
    Uncorrected = 13
    Delayed = 14
    Detected = 15
    NoAction = 16
    Logged = 17
    Tagged = 18
    Alert = 19
    Count = 20
    Reset = 21
    CaptchaRequired = 22
    ChallengeRan = 23
    AccessRevoked = 24
    Rejected = 25
    Unauthorized = 26
    Error = 27
    Other = 99


class Finding(BaseEvent, BaseModel):
    """
    The Finding event is a generic event that defines a set of attributes available in the Findings category.

    Attributes:
    - Activity (activity_name) [Optional]: The finding activity name, as defined by the activity_id.
    - Activity ID (activity_id): The normalized identifier of the finding activity.
    - Comment (comment) [Optional]: A user provided comment about the finding.
    - Confidence (confidence) [Optional]: The confidence, normalized to the caption of the confidence_id value. In the case of 'Other', it is defined by the event source.
    - Confidence ID (confidence_id) [Optional]: Represents the accuracy of the detection rule. A low confidence indicates a broad finding scope that may include benign events.
    - Confidence Score (confidence_score) [Optional]: The confidence score as reported by the event source.
    - End Time (end_time) [Optional]: Time of the latest event included in the finding.
    - End Time DT (end_time_dt) [Optional]: Time of the latest event included in the finding in datetime format.
    - Finding Information (finding_info) [Required]: Describes the supporting information about a generated finding.
    - Start Time (start_time) [Optional]: Time of the earliest event included in the finding.
    - Start Time DT (start_time_dt) [Optional]: Time of the earliest event included in the finding in datetime

    """

    activity_name: Optional[str]
    activity_id: ActivityID
    comment: Optional[str]
    confidence: Optional[str]
    confidence_id: Optional[ConfidenceID]
    confidence_score: Optional[int]
    end_time: Optional[int]
    end_time_dt: Optional[datetime]
    finding_info: FindingInformation
    start_time: Optional[int]
    start_time_dt: Optional[datetime]
